---
- name: Configure My Linux
  gather_facts: true
  hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: role-install-tools

    - include_role:
        name: role-setup-terminal
